In [15]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

# 读取数据集
music_data = pd.read_csv('datasets/music.csv')
music_data

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [17]:
# 拆分出输出的数据集
X = music_data.drop(columns=['genre'])
X = X.values
X

array([[20,  1],
       [23,  1],
       [25,  1],
       [26,  1],
       [29,  1],
       [30,  1],
       [31,  1],
       [33,  1],
       [37,  1],
       [20,  0],
       [21,  0],
       [25,  0],
       [26,  0],
       [27,  0],
       [30,  0],
       [31,  0],
       [34,  0],
       [35,  0]])

In [ ]:
# 拆分出输出的数据集
y = music_data['genre']

In [ ]:
# 训练模型
model = DecisionTreeClassifier()
model.fit(X, y)

In [ ]:
# 预测21岁男性喜欢的音乐类型 和 22岁女性喜欢的音乐类型
predictions = model.predict([ 
    [21, 1], 
    [22, 0] 
])
predictions